
(()=>{'use strict';
const D=window.EBOOK_DATA;
const app=document.getElementById('app');
const langLabels={zh:'中文',en:'English',ja:'日本語'};
const themeKeys=['aurora','night','warm','grid'];
const ui={
 zh:{eyebrow:'Commercial Vehicle Research Library',works:'論文集',marquee:'論文跑馬燈',catalog:'目錄',language:'語言',themes:'版型',home:'首頁',read:'閱讀論文',more:'顯示完整摘要',prompt:'影像提示詞',promptLibrary:'Prompt 區｜論文形象圖繪製提示詞',close:'關閉',back:'返回論文集',word:'字數',keywords:'關鍵字',protected:'線上閱讀版已停用文字選取、複製、右鍵、列印與下載入口。',toc:'章節目錄',heroPrompt:'首頁形象圖提示詞',imgPath:'圖片路徑',footer:'本網站為純靜態線上電子書瀏覽版，未包含原始 Word 檔案與下載連結。'},
 en:{eyebrow:'Commercial Vehicle Research Library',works:'Thesis Collection',marquee:'Thesis Carousel',catalog:'Catalog',language:'Language',themes:'Themes',home:'Home',read:'Read Thesis',more:'Full Abstract',prompt:'Image Prompt',promptLibrary:'Prompt Area | Editorial Thesis Image Prompts',close:'Close',back:'Back to Library',word:'Word count',keywords:'Keywords',protected:'The online reading version disables selection, copy, right-click, print, and document download entries.',toc:'Chapter Contents',heroPrompt:'Homepage visual prompt',imgPath:'Image path',footer:'This is a static online e-book reading version. Original Word files and download links are not included.'},
 ja:{eyebrow:'Commercial Vehicle Research Library',works:'論文集',marquee:'論文カルーセル',catalog:'目次',language:'言語',themes:'テーマ',home:'ホーム',read:'論文を読む',more:'完全な要旨',prompt:'画像プロンプト',promptLibrary:'Prompt エリア｜論文イメージ画像プロンプト',close:'閉じる',back:'論文集へ戻る',word:'文字数',keywords:'キーワード',protected:'オンライン閲覧版では、文字選択、コピー、右クリック、印刷、文書ダウンロード導線を無効化しています。',toc:'章節目次',heroPrompt:'ホーム画像プロンプト',imgPath:'画像パス',footer:'このサイトは静的なオンライン電子書籍閲覧版であり、元のWordファイルやダウンロードリンクは含まれていません。'}
};
const themes={zh:['清爽玻璃','夜間閱讀','暖色紙本','網格研究'],en:['Aurora Glass','Night Reading','Warm Paper','Research Grid'],ja:['透明ガラス','夜間閲覧','暖色紙面','研究グリッド']};
let state={lang:localStorage.getItem('ebookLang')||'zh',theme:localStorage.getItem('ebookTheme')||'aurora',view:'home',paperId:null};
let carouselApi=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function t(k){return ui[state.lang][k]||ui.zh[k]||k;}
function imgURL(name){return 'images/'+encodeURIComponent(name).replace(/%2F/g,'/');}
function clip(s,n=260){const a=[...String(s||'')];return a.length<=n?s:a.slice(0,n).join('')+'……';}
function kwChips(s){return String(s||'').split(/[；;，,]/).map(x=>x.trim()).filter(Boolean).map(k=>`<span class="keyword">${esc(k)}</span>`).join('');}
function paperOtherTitles(p){return `<div class="paper-subtitle">EN｜${esc(p.titles.en)}<br>JA｜${esc(p.titles.ja)}</div>`;}
function setLang(l){state.lang=l;localStorage.setItem('ebookLang',l);document.documentElement.lang=l==='zh'?'zh-Hant':l==='ja'?'ja':'en';render();}
function setTheme(th){state.theme=th;localStorage.setItem('ebookTheme',th);document.body.dataset.theme=th;document.querySelectorAll('[data-theme]').forEach(x=>x.classList.toggle('active',x.dataset.theme===th));}
function scrollToCard(id){const el=document.getElementById(id);if(!el)return;const header=document.querySelector('.topbar');const topOffset=(header?header.getBoundingClientRect().height:0)+28;const y=el.getBoundingClientRect().top+window.scrollY-topOffset;window.scrollTo({top:Math.max(0,y),behavior:'smooth'});history.replaceState(null,'','#'+id);el.classList.remove('focus-flash');void el.offsetWidth;el.classList.add('focus-flash');setTimeout(()=>el.classList.remove('focus-flash'),1800);}
function showModal(title, body){const m=document.getElementById('modal');m.querySelector('.modal-title').textContent=title;m.querySelector('.modal-body').textContent=body;m.classList.add('open');}
function closeModal(){const m=document.getElementById('modal');if(m)m.classList.remove('open');}
function render(){document.body.dataset.theme=state.theme;document.documentElement.lang=state.lang==='zh'?'zh-Hant':state.lang==='ja'?'ja':'en'; if(state.view==='reader'&&state.paperId){renderReader(state.paperId)}else renderHome();}
function renderHome(){if(carouselApi&&carouselApi.stop)carouselApi.stop(); const papers=D.papers;app.innerHTML=`<div class="site">
<header class="topbar"><div class="brandline"><div class="eyebrow">${esc(t('eyebrow'))}</div><div class="copyright">${esc(D.site.copyright)}</div></div><div class="controls">${Object.keys(langLabels).map(k=>`<button class="pill ${state.lang===k?'active':''}" data-lang="${k}">${langLabels[k]}</button>`).join('')}${themeKeys.map((k,i)=>`<button class="theme-btn ${state.theme===k?'active':''}" data-theme="${k}">${esc(themes[state.lang][i])}</button>`).join('')}</div></header>
<main><section class="hero" id="home"><div class="hero-copy"><div class="eyebrow">${esc(t('eyebrow'))}</div><h1>${esc(D.site.title[state.lang])}</h1><p class="subtitle">${esc(D.site.subtitle[state.lang])}</p><div class="hero-note">${esc(t('protected'))}</div></div><div class="hero-image-wrap"><img class="hero-img" src="${esc(D.site.heroImage)}" draggable="false" alt="${esc(D.site.title[state.lang])}"></div></section>
<section class="carousel-section" id="marquee"><div class="carousel-shell" id="carouselShell"><div class="carousel-stage" id="carouselStage">${papers.map((p,i)=>`<button class="carousel-item" data-target="${p.id}" data-index="${i}" style="--thumb:url('${imgURL(p.image)}')"><span>${i+1}. ${esc(p.titles[state.lang])}</span></button>`).join('')}</div><div class="carousel-hint">${esc(t('works'))}</div></div></section>
<section id="works"><div class="section-title"><h2>${esc(t('works'))}</h2><p>${esc(t('footer'))}</p></div><div class="library-grid">${papers.map((p,i)=>card(p,i)).join('')}</div></section>
</main><footer class="footer">${esc(t('footer'))}<br>${esc(D.site.copyright)}</footer></div>${floating()}${modal()}`;bindHome();initCarousel();}
function card(p,i){return `<article class="paper-card" id="${p.id}"><a class="image-link" href="#${p.id}" data-scroll-card="${p.id}" aria-label="${esc(p.titles[state.lang])}"><img class="card-img" src="${imgURL(p.image)}" draggable="false" alt="${esc(p.titles[state.lang])}"></a><div class="paper-body"><div class="paper-topline"><div class="paper-index">Thesis ${String(i+1).padStart(2,'0')}</div><div class="word-count">${esc(t('word'))}：${Number(p.wordCount).toLocaleString()}</div></div><h3 class="paper-title">${esc(p.titles[state.lang])}</h3>${paperOtherTitles(p)}<p class="summary">${esc(clip(p.abstract,260))}</p><div class="keywords"><strong class="keyword">${esc(t('keywords'))}</strong>${kwChips(p.keywords)}</div><div class="card-actions"><button class="reader-btn" data-read="${p.id}">${esc(t('read'))}</button><button class="more-btn" data-abstract="${p.id}">${esc(t('more'))}</button></div></div></article>`;}
function floating(){const papers=D.papers;return `<div class="floating"><div class="float-panel" id="langPanel"><h4>${esc(t('language'))}</h4><div class="lang-grid">${Object.keys(langLabels).map(k=>`<button class="pill ${state.lang===k?'active':''}" data-lang="${k}">${langLabels[k]}</button>`).join('')}</div></div><div class="float-panel" id="floatPanel"><h4>${esc(t('catalog'))}</h4><a href="#home">${esc(t('home'))}</a><a href="#works">${esc(t('works'))}</a>${papers.map((p,i)=>`<a href="#${p.id}" data-float-card="${p.id}">${i+1}. ${esc(p.titles[state.lang])}</a>`).join('')}<h4>${esc(t('themes'))}</h4><div class="theme-grid">${themeKeys.map((k,i)=>`<button class="theme-btn ${state.theme===k?'active':''}" data-theme="${k}">${esc(themes[state.lang][i])}</button>`).join('')}</div></div><div class="floating-language-row"><button class="float-lang-btn" id="langToggle">${esc(t('language'))}</button></div><div class="float-actions"><button class="menu-btn" id="menuToggle">${esc(t('catalog'))}</button><button class="menu-btn" id="topBtn">↑</button></div></div>`;}
function modal(){return `<div class="modal" id="modal" role="dialog" aria-modal="true"><div class="modal-card"><button class="modal-close" aria-label="${esc(t('close'))}">×</button><h3 class="modal-title"></h3><div class="modal-body"></div></div></div>`;}
function bindCommon(){document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));const menu=document.getElementById('floatPanel'),lang=document.getElementById('langPanel');const mt=document.getElementById('menuToggle'),lt=document.getElementById('langToggle'),top=document.getElementById('topBtn');if(mt)mt.onclick=()=>{menu.classList.toggle('open');lang.classList.remove('open')};if(lt)lt.onclick=()=>{lang.classList.toggle('open');menu.classList.remove('open')};if(top)top.onclick=()=>scrollTo({top:0,behavior:'smooth'});document.querySelectorAll('.modal-close').forEach(b=>b.onclick=closeModal);const m=document.getElementById('modal');if(m)m.onclick=e=>{if(e.target.id==='modal')closeModal()};}
function bindHome(){bindCommon();document.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>{state.view='reader';state.paperId=b.dataset.read;history.pushState(null,'','#read-'+state.paperId);render();scrollTo({top:0})});document.querySelectorAll('[data-abstract]').forEach(b=>b.onclick=()=>{const p=D.papers.find(x=>x.id===b.dataset.abstract);showModal(p.titles[state.lang],p.abstract+'\n\n'+t('keywords')+'：'+p.keywords)});document.querySelectorAll('[data-scroll-card],[data-float-card]').forEach(a=>a.onclick=e=>{e.preventDefault();scrollToCard(a.dataset.scrollCard||a.dataset.floatCard)});document.querySelectorAll('.carousel-item').forEach(b=>b.addEventListener('click',e=>{const shell=document.getElementById('carouselShell');if(shell&&shell.dataset.dragging==='1')return;e.preventDefault();scrollToCard(b.dataset.target)}));}
function renderReader(id){if(carouselApi&&carouselApi.stop)carouselApi.stop();const p=D.papers.find(x=>x.id===id)||D.papers[0];app.innerHTML=`<div class="reader-view"><header class="reader-header"><button class="back-btn" id="backHome">← ${esc(t('back'))}</button><div class="reader-title-block"><h1>${esc(p.titles[state.lang])}</h1><div class="reader-subtitle">${esc(D.site.copyright)} ｜ ${esc(t('word'))}：${Number(p.wordCount).toLocaleString()}</div></div><div class="controls">${Object.keys(langLabels).map(k=>`<button class="pill ${state.lang===k?'active':''}" data-lang="${k}">${langLabels[k]}</button>`).join('')}${themeKeys.map((k,i)=>`<button class="theme-btn ${state.theme===k?'active':''}" data-theme="${k}">${esc(themes[state.lang][i])}</button>`).join('')}</div></header><div class="reader-layout"><aside class="reader-toc"><h2>${esc(t('toc'))}</h2>${p.toc.map(h=>`<a class="l${h.level}" href="#${h.id}">${esc(h.title)}</a>`).join('')}</aside><main class="reader-paper"><article class="ebook-article" id="readerArticle">${p.html}</article></main></div></div>${floating()}${modal()}`;bindReader();}
function bindReader(){bindCommon();document.getElementById('backHome').onclick=()=>{state.view='home';state.paperId=null;history.pushState(null,'','#works');render();setTimeout(()=>document.getElementById('works')?.scrollIntoView(),50)};document.querySelectorAll('.reader-toc a').forEach(a=>a.onclick=e=>{e.preventDefault();document.getElementById(a.getAttribute('href').slice(1))?.scrollIntoView({behavior:'smooth',block:'start'});});}
function initCarousel(){const shell=document.getElementById('carouselShell');const cards=[...document.querySelectorAll('.carousel-item')];if(!shell||!cards.length)return;let offset=0,baseSpeed=.0045,speed=baseSpeed,targetSpeed=baseSpeed,raf=0,dragging=false,lastX=0,lastT=0,dragVelocity=0;const n=cards.length;function dimensions(){const w=shell.clientWidth||window.innerWidth;const radius=Math.min(Math.max(w*.36,260),560);return{w,radius}}function update(){const d=dimensions(),now=performance.now();if(!lastT)lastT=now;const dt=Math.min(42,now-lastT);lastT=now;speed+=(targetSpeed-speed)*.08;if(!dragging)offset+=speed*dt/16.67+dragVelocity;dragVelocity*=.92;const tau=Math.PI*2;cards.forEach((card,i)=>{let theta=((i-offset)/n)*tau,z=Math.cos(theta),x=Math.sin(theta)*d.radius,scale=.62+((z+1)/2)*.46,opacity=.26+((z+1)/2)*.74,rotateY=-Math.sin(theta)*34,blur=z<-.35?1.2:0;card.style.transform=`translate(-50%,-50%) translateX(${x.toFixed(2)}px) scale(${scale.toFixed(3)}) rotateY(${rotateY.toFixed(2)}deg)`;card.style.zIndex=String(Math.round((z+1)*100));card.style.opacity=String(opacity.toFixed(3));card.style.filter=`blur(${blur}px)`});raf=requestAnimationFrame(update)}function pointerSpeed(clientX){const r=shell.getBoundingClientRect(),rel=(clientX-r.left)/Math.max(1,r.width);if(rel<.32)targetSpeed=-.035;else if(rel>.68)targetSpeed=.035;else targetSpeed=baseSpeed}shell.addEventListener('mousemove',e=>pointerSpeed(e.clientX));shell.addEventListener('mouseleave',()=>{targetSpeed=baseSpeed});shell.addEventListener('pointerdown',e=>{const tapped=e.target.closest?e.target.closest('.carousel-item'):null;dragging=true;lastX=e.clientX;dragVelocity=0;shell.dataset.dragging='0';shell.dataset.downX=String(e.clientX);shell.dataset.downY=String(e.clientY);shell.dataset.tapTarget=tapped?tapped.dataset.target:'';shell.setPointerCapture&&shell.setPointerCapture(e.pointerId)});shell.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-lastX;lastX=e.clientX;const startX=Number(shell.dataset.downX||e.clientX);if(Math.abs(e.clientX-startX)>8)shell.dataset.dragging='1';const d=dimensions(),delta=dx/Math.max(240,d.radius)*1.9;offset-=delta;dragVelocity=-delta*.08;targetSpeed=delta>0?-.045:.045});const endDrag=e=>{const was=shell.dataset.dragging==='1',target=shell.dataset.tapTarget||'',startX=Number(shell.dataset.downX||0),startY=Number(shell.dataset.downY||0),dx=e&&typeof e.clientX==='number'?Math.abs(e.clientX-startX):999,dy=e&&typeof e.clientY==='number'?Math.abs(e.clientY-startY):999;dragging=false;if(e&&e.type==='pointerup'&&!was&&target&&dx<10&&dy<14){e.preventDefault();scrollToCard(target)}setTimeout(()=>{targetSpeed=baseSpeed;shell.dataset.dragging='0';shell.dataset.tapTarget=''},180)};shell.addEventListener('pointerup',endDrag);shell.addEventListener('pointercancel',endDrag);shell.addEventListener('lostpointercapture',endDrag);raf=requestAnimationFrame(update);carouselApi={stop:()=>cancelAnimationFrame(raf)}}
['contextmenu','copy','cut','dragstart','selectstart'].forEach(evt=>document.addEventListener(evt,e=>e.preventDefault(),{capture:true}));
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&['c','u','s','p','a','x'].includes(e.key.toLowerCase()))e.preventDefault();if(e.key==='F12')e.preventDefault();if(e.key==='Escape')closeModal();});
window.addEventListener('popstate',()=>{if(location.hash.startsWith('#read-')){state.view='reader';state.paperId=location.hash.replace('#read-','');}else{state.view='home';state.paperId=null;}render();});
if(location.hash.startsWith('#read-')){state.view='reader';state.paperId=location.hash.replace('#read-','');}
render();
})();
